<div class="straker-about-page">
    <div>
        <a href="https://www.strakertranslations.com" target="_blank"><img src="https://www.strakertranslations.com/assets/images/logo.png" alt="Straker Translations"></a>
    </div>
    <br>
    <div>
        <p><b>Extension Version</b>: <?php echo $block->getModuleVersion() ?></p>
    </div>
    <hr>
    <div>
        <p>Our API-based extension enables you to translate your Magento content by professional linguists with market expertise, all without having to import or export any files. The entire process, including the publishing of the translated content, is done via our extension’s UI. More information can be found in our <a href="https://support.strakertranslations.com/extensions/magento2/" title="Straker Doc - Magento2" target="_blank">knowledge page</a>.</p>
    </div>
</div>

