<!--Renders everything from parent template first -->
<?php
/**
 * @var \Magento\Backend\Block\Widget\Grid\Extended $block
 */
//phpcs:disable
include($block->getTemplateFile('Magento_Backend::widget/grid/extended.phtml'));
//phpcs:enable
?>

<!--After rendering parent template, more options are inserted via frontend DOM manipulation -->
<?php if ($block->getPagerVisibility()): ?>
    <script type="text/javascript">
        var selectElement = document.getElementById("<?= $block->escapeHtml($block->getHtmlId()) ?>_page-limit");

        selectElement.innerHTML += "<option value='500'<?php if ($block->getCollection()->getPageSize() == 500): ?>
        selected='selected'<?php endif; ?>>500</option>"

        selectElement.innerHTML += "<option value='750'<?php if ($block->getCollection()->getPageSize() == 750): ?>
        selected='selected'<?php endif; ?>>750</option>"

         selectElement.innerHTML += "<option value='800'<?php if ($block->getCollection()->getPageSize() == 800): ?>
        selected='selected'<?php endif; ?>>800</option>"

        selectElement.innerHTML += "<option value='850'<?php if ($block->getCollection()->getPageSize() == 850): ?>
        selected='selected'<?php endif; ?>>850</option>"

        selectElement.innerHTML += "<option value='900'<?php if ($block->getCollection()->getPageSize() == 900): ?>
        selected='selected'<?php endif; ?>>900</option>"

        selectElement.innerHTML += "<option value='950'<?php if ($block->getCollection()->getPageSize() == 950): ?>
        selected='selected'<?php endif; ?>>950</option>"
    </script>
<?php endif ?>