<?php
/** @var $block \Straker\EasyTranslationPlatform\Block\Adminhtml\Job\Index */
?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Ui/js/modal/alert',
        'Magento_Ui/js/modal/confirm'
    ], function ($) {
        var myAccountButton = $('.straker-my-account-button');

        if( typeof myAccountButton.get(0) !== 'undefined' ){
            var url = '<?= $block->_getMyAccountUrl(); ?>';
            myAccountButton.on('click', function (e) {
                e.preventDefault();
                window.open(url, '_blank');
            });
        }
    });

</script>