<section id="job-summary" class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><strong>SUMMARY</strong></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item">
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tbody>
                        <tr>
                            <th><?php echo __('Product') ?></th>
                            <td class="products">0</td>
                        </tr>
                        <tr>
                            <th><?php echo __('Category') ?></th>
                            <td class="categories">0</td>
                        </tr>
                        <tr>
                            <th><?php echo __('CMS Page') ?></th>
                            <td class="pages">0</td>
                        </tr>
                        <tr>
                            <th><?php echo __('CMS Block') ?></th>
                            <td class="blocks">0</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>