<?php /** @var \Straker\EasyTranslationPlatform\Block\Adminhtml\Settings\Config\ResetAccountButton $block */ ?>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm'
    ], function( $, confirm ){

        var $resetButton = $('#demonstration_data_reset_account_button');

        $resetButton.on('click', function(){

            confirm({
                title: '<?= $block->escapeHtml(__("Please Confirm")); ?>',
                content: '<?= $block->escapeHtml(__("This will remove all Straker Translations data, 
                including registration, settings, translations and jobs.")) ?>',
                actions: {
                    confirm: function(){
                        $.ajax({
                            url      : '<?= $block->escapeUrl($block->getAjaxResetUrl()); ?>',
                            method   : 'get',
                            dataType : 'json',
                            showLoader :  true,
                            complete : function(){
                                location.reload();
                            }
                        });
                    }
                }
            });
        });
    });
</script>

<?= $block->getButtonHtml(); ?>
    <?= '<p class="note"><span>'
            . $block->escapeHtml(
                __('This will remove all of the saved data, including 
                    registration, settings, translated text and jobs.')
            )
            . '</span></p>';