<table>
    <?php
    $hasLanguageSetting = false;
    /** @var \Straker\EasyTranslationPlatform\Block\Adminhtml\Settings\Config\ResetStore $block */
    foreach ($block->getWebsites() as $website) {
        $groups = $website->getGroups();

        if (count($groups) > 0) {
            foreach ($website->getGroups() as $group) { ?>
                <tr>
                    <td colspan="4" class="site-group-name">
                        <span>
                            <?= $block->escapeHtml(
                                __($website->getName())
                                . ' - '
                                . __($group->getName())
                            ); ?>
                        </span>
                    </td>
                </tr>
                <?php $stores = $group->getStores();
                if (count($stores) > 0) {
                    $count = 0;
                    foreach ($stores as $store) {
                        if ($store->getId() != \Magento\Store\Model\Store::DEFAULT_STORE_ID) {
                            $storeData = $block->getStoreLanguageSetting($store->getId());
                            if ($storeData) {
                                $count++;
                                $hasLanguageSetting = true;
                                ?>
                                <tr class="store-view-list">
                                    <td class="store-view-name">
                                        <span>
                                            <?= $block->escapeHtml(__($storeData['source']->getName())) ?>
                                        </span>
                                        <p class="store-language">
                                            [<?= $block->escapeHtml($storeData['source_language']); ?>]
                                        </p>
                                    </td>
                                    <td>
                                        <i class="fa fa-angle-right" aria-hidden="true"></i>
                                    </td>
                                    <td class="store-view-name">
                                        <span>
                                            <?= $block->escapeHtml(__($store->getName())) ?>
                                        </span>
                                        <p class="store-language">
                                            [<?= $block->escapeHtml($storeData['target_language']); ?>]
                                        </p>
                                    </td>
                                    <td class="clear-language">
                                        <input type="hidden"
                                               name="store-id"
                                               value="<?= $block->escapeHtml($store->getId()); ?>"/>
                                        <?= $block->getRemoveTranslationButtonHtml($store) ?>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php }
                    } ?>
                    <?php if ($count === 0): ?>
                        <tr class="store-view-list">
                            <td colspan="4">
                                <span><?= $block->escapeHtml(__("No language settings have been setup.")); ?></span>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <?php
                } else { ?>
                    <tr class="store-view-list">
                        <td colspan="4">
                            <span><?= $block->escapeHtml(__("No store views for this website.")); ?></span>
                        </td>
                    </tr>
                    <?php
                }
            }
        } else { ?>
            <tr>
                <td colspan="4">
                    <span class="site-group-name">
                        <?= $block->escapeHtml($website->getName()); ?>
                    </span>
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    <span> <?= $block->escapeHtml(__("No stores for this website.")); ?> </span>
                </td>
            </tr>
        <?php } ?>
        <tr>
            <td colspan="4">
                <p class="straker-space-line"></p>
            </td>
        </tr>
    <?php } ?>
    <?php if ($hasLanguageSetting): ?>
    <tr>
        <td class="all-store-view-name">
            <b>All Store Views</b>
        </td>
        <td colspan="3" align="right" class="clear-language">
            <?= $block->getRemoveAllTranslationButtonHtml(); ?>
        </td>
    </tr>
    <?php endif; ?>
</table>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'Magento_Ui/js/modal/confirm'
    ], function ($, alert, confirm) {
        var $resetButton = $('.action-default.scalable.straker-reset-store-button');
        var $resetAllButton = $('#straker_reset_all_store_button');

        //disable save config button
        // var saveButton = $('.save');
        // if (saveButton.get(0) !== 'undefined') {
        //     saveButton.prop('disabled', 'disabled');
        // }

        //reset language settings for all store views
        $resetAllButton.on('click', function (e) {
            e.preventDefault();
            confirm({
                title: '<?= $block->escapeHtml(__("Please Confirm")) ?>',
                content: '<?= $block->escapeHtml(__('Do you want to reset settings for all store views?')) ?>',
                actions: {
                    confirm: function () {
                        $.ajax({
                            url: '<?= $block->escapeUrl($block->getAjaxResetUrl()); ?>',
                            method: 'get',
                            showLoader: true,
                            complete: function () {
                                location.reload();
                            }
                        });
                    }
                }
            });
        });

        //reset language settings for a specific store view
        $resetButton.on('click', function (e) {
            e.preventDefault();

            var iStoreId = $(this).siblings('input[name=store-id]').val();

            if ($.isNumeric(iStoreId) && iStoreId > 0) {

                confirm({
                    title: '<?= $block->escapeHtml(__("Please Confirm")) ?>',
                    content: '<?= $block->escapeHtml(__('Do you want to reset settings for this store view?')) ?>',
                    actions: {
                        confirm: function () {
                            $.ajax({
                                url: '<?= $block->escapeHtml($block->getAjaxResetUrl()); ?>',
                                data: {'store': iStoreId},
                                method: 'get',
                                showLoader: true,
                                complete: function () {
                                    location.reload();
                                }
                            });
                        }
                    }
                });

            } else {
                alert({
                    content: '<?= $block->escapeHtml(__('Store code is not valid.')); ?>',
                });
            }
        });
    });
</script>





