<?php
use \Straker\EasyTranslationPlatform\Block\Adminhtml\Settings\Config\CompleteJob;

/** @var CompleteJob $block */
echo $block->getButtonHtml();
?>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'Magento_Ui/js/modal/confirm'
    ], function( $, alert, confirm ){

        var saveButton = $('.save');
        var translateButton = $('#demonstration_complete_job_translate_job');

        if( saveButton.get(0) !== 'undefined' ){
            saveButton.prop('disabled','disabled');
        }

        translateButton.on('click', function ( e ) {
            var tjNumberInput = $('#demonstration_complete_job_tj_number');
            var tjNumber = tjNumberInput.val();
            $.ajax({
                url: '<?= $block->escapeUrl($block->getUrl('EasyTranslationPlatform/Jobs/CompleteJob')); ?>',
                method: 'get',
                data: { job_id: tjNumber },
                dataType: 'json',
                showLoader: true
            }).done(function (data, textStatus ) {
                if( textStatus === 'success' && data.success ) {
                    alert({
                        title: '',
                        content: '<?= $block->escapeHtml(__('Job completed successfully.')); ?>'
                    });
                    tjNumberInput.val('');
                    location.href = "<?= $block->escapeUrl($block->getUrl('EasyTranslationPlatform/Jobs/Index')); ?>";
                }else{
                    alert({
                        title: '',
                        content: '<?= $block->escapeHtml(__('Failed to complete the job.')); ?>'
                    });
                }
            });
        });
    });
</script>
